name: build pr

on:
  pull_request:
    branches: [ main ]

env:
  FORCE_COLOR: 2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        bun-version: ['1.3']

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Use Bun ${{ matrix.bun-version }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ matrix.bun-version }}
    - run: bun install
    - run: |
        echo "::remove-matcher owner=eslint-compact::"
        echo "::remove-matcher owner=eslint-stylish::"
    - run: bun run all
    - name: Commit built data
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "GitHub Actions"
        git add -A data
        git diff --cached --exit-code || git commit -m "build"
        git push
